### ISSUE TITLE
Add Control Room environmental controls

### ISSUE THREAD

**Issue by moemyself3** [rcamuccio/Ninnion#14]
Section should include:
- [ ] Labeled images of controls, buttons, and displays
- [ ] Instructions on setting heating and cooling

**Comment by rcamuccio** [comment]
I'm adding notes regarding the heater from Rudy.

Our A/C unit also doubles as a heater when put into the correct mode using the black remote mounted on the wall. 
- Simply press the mode button on the A/C remote and you will be able to see on the left side of the display that the remote is cycling through the settings it has. Continue pressing until you see a image that looks like a sun which should be displayed at the bottom left corner. 
- You can also confirm by noticing a red light under the power light that shows the A/C unit is in heater mode. 
- You are then able to adjust the heat by simply raising or lowering the temperature on the remote with the up and down bottoms. 
- HEATER WILL NOT KICK ON IMMEDIATELY. AROUND 5 MINUTES MUST BE GIVEN BEFORE HEATER IS TURNED ON.
